name: packtracker

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Scala
        uses: olafurpg/setup-scala@v2
        with:
          java-version: 1.8
      - name: Export assets to packtracker
        if: github.event_name == 'pull_request'
        run: |
          sbt seqexec_web_client/fullOptJS::webpack
          cd modules/seqexec/web/client/target/scala-2.12/scalajs-bundler/main/
          node node_modules/webpack/bin/webpack --bail --profile --json --config packtracker.webpack.config.js
        env:
          SBT_OPTS: "-Xmx4096M -Xss2M -XX:ReservedCodeCacheSize=256M -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
          PT_COMMIT: ${{ github.event.pull_request.head.sha }}
          PT_PRIOR_COMMIT: ${{ github.event.pull_request.base.sha }}
      - name: Export assets to packtracker merged
        if: github.event_name == 'push'
        run: |
          sbt seqexec_web_client/fullOptJS::webpack
          cd modules/seqexec/web/client/target/scala-2.12/scalajs-bundler/main/
          node node_modules/webpack/bin/webpack --bail --profile --json --config packtracker.webpack.config.js
        env:
          SBT_OPTS: "-Xmx4096M -Xss2M -XX:ReservedCodeCacheSize=256M -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
          PT_COMMIT: ${{ github.sha }}
